### ISSUE TITLE
Unable to setup timesaver plugin

### ISSUE THREAD

**Issue by Alok650** [tduniec/backstage-timesaver-plugin#2] opened 2024-02-05 16:20 UTC
**Issue:**
I have configured time saver plugin - frontend & backend
However, on <URL>/time-saver, I am getting 404 for all the time-saver endpoint. In my Postgres, DB for this plugin is not getting created.

**Ref. image**
<img width="1490" alt="image" src="https://github.com/tduniec/backstage-timesaver-plugin/assets/58817460/e919897e-5103-41d7-98e0-ce3177fb8a8f">

Added in template.yaml:
`metadata:
    substitute:
      engineering:
        sre: 1
        security: 1
        development_teams: 2`

**Comment by tduniec** [comment] 2024-02-05 17:48
Hey,

thank you for interest in plugin. 

can you confirm the migration file was executed on your backend init ? 
can you see database or schema ? 

What kind of error you are getting. Seems like the plugin is not available on backend. 

Please tell me the output of:
Localhost:7007/api/time-saver/health

**Comment by Alok650** [comment] 2024-02-06 05:22
The above was fixed. Issue was with the backend plugin setup (package version mismatch).

Another issue:
In my template.yaml, I have written time-saved ie.

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-service-onboarding
  title: New Service Onboarding
  description: Onboards a new microservice
  substitute:
    engineering:
     develops: 1
      security: 1
      development_teams: 2
```

but currently its not getting ingested into the time-saver plugin (don't see any change in UI).


Questions:
1. is substitute necessary in the yaml?
2. How does the ingestion for these metrics happen? is it a push based mech. where every time some triggers a execution, it will push metrics from that template into time-saver db. or is it based on polling (if so, can I configure at what interval the pull from /create/tasks would happen)
3. Do the groups defined in the template yaml need to be ingested as group entities in the catalog?

**Comment by toma2395** [comment] 2024-02-06 07:47
Hello @Alok650, 

I hope we can quickly fix this and you will be able to use time-saver.

1. Yes, this substitute part is necessary, then once you execute the template with its substitution values your data should be also available in time-saver. Every 5 minutes there is a scheduled job that is regenerating the stats. But you can also call it manually by HTTP

${yourIp}:{post}/api/time-saver/generateSavings , method GET

Please let me know if you notice something in logs, any error or warning regarding the time-saver ? 

2. This is scheduled polling mechanism, you can execute it manually with instruction above. 
It also runs every 5 minutes 

3. No this doesn't have to match, there is not required dependency to catalog groups. But there is an idea to add timesaver components to Groups entity page in future releases. 

Please let me know if the issue is fixed or provide more details like logs, error responses, evidences that will help me debug it. We can also jump on the call and quickly go through that and resolve the issue. This will also help me improve the manuals for time-saver.

**Comment by toma2395** [comment] 2024-02-06 09:33
@Alok650 

hey please update versions of plugin to latest one

**Comment by Alok650** [comment] 2024-02-06 09:41
@toma2395 
    "@tduniec/backstage-plugin-time-saver-backend": "^0.1.5",
    "@tduniec/backstage-plugin-time-saver-common": "^0.1.0",
    
   currently using this. what should I update to?

also currently getting no data on the time-saver dashboard.

I have hit http://localhost:7007/api/time-saver/generateSavings, which gives me response:
```
{
"status": "SUCCESS"
}
```

**Comment by toma2395** [comment] 2024-02-06 10:01
Hey, 

please use the newest versions since I have published a fix that may be fixing your problem. 

https://www.npmjs.com/package/@tduniec/backstage-plugin-time-saver-backend/v/0.1.7
https://www.npmjs.com/package/@tduniec/backstage-plugin-time-saver/v/0.1.5
https://www.npmjs.com/package/@tduniec/backstage-plugin-time-saver-common/v/0.1.1

ad let me know the output

**Comment by Alok650** [comment] 2024-02-07 06:01
Thanks @toma2395 . this is resolved. Look forward to new releases from the plugins - we can emit metrics on user and group entity level.

**Comment by tduniec** [comment] 2024-02-07 07:00
Thanks @Alok650 , closing the issue

**Closed as completed by tduniec** 2024-02-07 07:00 UTC
